# Generated by Django 3.1.14 on 2023-05-24 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20230428_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contact',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('houses', models.ManyToManyField(related_name='bookmarks', to='myapp.House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
